! Hardcoded directories for input / output
! ------- Input (READ-ONLY) directories
      CHARACTER (LEN=*), PARAMETER :: DATA_DIR='../../data/'
      CHARACTER (LEN=*), PARAMETER :: LC_LAI_GISS_DIR='../lc_lai_giss/'
      CHARACTER (LEN=*), PARAMETER :: LC_LAI_ENT_DIR='../lc_lai_ent/'
      CHARACTER (LEN=*), PARAMETER :: LC_LAI_FOR_1KM1KM_DIR=
     &     '../../lc_lai_for_1km1km/'

! ------- Output Directory

