! Assigns tree heights from Simard et al. (2011) to tree PFTs in 
! EntMM_lc_maxlai_#x#.bin generated by modis_entpftg.f.
!
! It assigns height to the cover fractions.  Both LAImax and Height
! are 1 km scale assignments to the 1 km subgrid cover fractions (all
! subgrid fractions in a 1 km grid cell get the same LAImax and
! Height, except for shrubs and grasses, which get assigned some
! ballpark heights).
!
! Author: Nancy Kiang, Carlo Monte, Elizabeth Fischer

! 1/2024 James Lui added in ifdef for GEDI heights
!-----------------------------------------------------------------
      
#ifdef JUST_DEPENDENCIES
#    define THIS_OUTPUTS_DIR MKFILES_DIR
#else
#    define THIS_OUTPUTS_DIR DEFAULT_OUTPUTS_DIR
#endif

#if (defined HGT_GEDI) || (defined HGT_POTAPOV)
program gedi
#else
program simard
#endif

    use netcdf
    use chunker_mod
    use ent_labels_mod
    use ent_params_mod

implicit none
      
    type(Chunker_t) :: chunker
    integer :: jchunk, ichunk    ! Index of current chunk
    integer :: jc, ic    ! Index WITHIN current chunk
    integer :: jj, ii            ! Index in full space

    ! ------ Inputs
    type(ChunkIO_t) :: io_sim    ! Simard heights
    type(ChunkIO_t), dimension(NENT20) :: io_lc
    ! ------ Outputs
    type(ChunkIO_t), dimension(NENT20) :: io_out
    type(ChunkIO_t) :: io_lchgt_checksum

    real*4 :: SHEIGHT, OHEIGHT
    type(FileInfo_t) :: info, overmeta
    integer :: k
#if (defined HGT_GEDI)
    integer, parameter :: hgt_year = 2020
    character*5, parameter :: hgt_ver = '1.1.2'
#elif (defined HGT_POTAPOV)
    integer, parameter :: hgt_year = 2021
    character*5, parameter :: hgt_ver = '1.1.3'
#endif

call clear_file_info(overmeta)
#if (defined HGT_GEDI)
overmeta%global_data_source = "hgt: P. Potapov et al. (2020) Mapping and monitoring global "// &
  "forest canopy height through integration of GEDI and Landsat data. Remote Sensing of Environment,"// &
  " 112165. https://doi.org/10.1016/j.rse.2020.112165"
overmeta%data_source = "hgt: GEDI heights (Landsat) (P. Potapov et al. 2020, https://doi.org/10.1016/j.rse.2020.112165)"
#elif (defined HGT_POTAPOV)
overmeta%global_data_source = "Potapov et  al. (2021) Remote Sensing of "// &
   "Environment, Volume 253. https://doi.org/10.1016/j.rse.2020.112165. Landsat/GEDI "// &
   "30 m global forest heights upscaled to 1 km mean and standard deviation. "// &
   "Personal communication, Peter Potapov, potapov@umd.edu."
overmeta%data_source = "hgt: GEDI heights (Landsat) (P. Potapov et al. 2020, https://doi.org/10.1016/j.rse.2020.112165)"
#else
overmeta%global_data_source = "hgt:  RH100 heights (Simard et al. 2011, doi:10.1029/2011jg001708)"
#endif
call init_ent_labels

! -----------------------------------------------------
! -----------------------------------------------------

call chunker%init(IM1km, JM1km, IMH*2,JMH*2, 'forplot', 100, 120, 10, outputs_dir=THIS_OUTPUTS_DIR)

! ----------------------------------------------------------------------
!     GET NC FILES IDs

! ------------- Inputs     
!     SIMARD HEIGHTS
call chunker%nc_open_input(io_sim, &
    INPUTS_URL, INPUTS_DIR, &
    'height/', &
#if (defined HGT_GEDI)
    'V1km_Forest_height_GEDILandsat.nc', 'heights', &
#elif (defined HGT_POTAPOV)
    'V1km_forest_height_Potapov2021.nc', 'heights', &
#else
    'simard_forest_heights.nc', 'heights', &
#endif
     1 )

!     ENTPFTLC
call chunker%nc_open_set(ent20, io_lc, &
    LAI_SOURCE, 'M', 'lc', LAI_YEAR, 'ent17', '1.1')

! ---------------- Outputs
! ENTPFT heights

call chunker%nc_create_set( &
    ent20, io_out, lc_weights(io_lc, 1d0, 0d0), &
#if (defined HGT_GEDI) || (defined HGT_POTAPOV)
    LAI_SOURCE, 'Ha', 'hgt', hgt_year, 'ent17', hgt_ver, &
#else
    LAI_SOURCE, 'M', 'hgt', LAI_YEAR, 'ent17', '1.1', &
#endif
    overmeta=overmeta)

! ---------- Checksums
#if (defined HGT_GEDI) || (defined HGT_POTAPOV)
call chunker%file_info(info, ent20, LAI_SOURCE, 'Ha', 'lchgt', hgt_year, 'ent17', hgt_ver, &
    varsuffix='_checksum')
info%global_data_source = overmeta%global_data_source
info%data_source = overmeta%data_source
#else
call chunker%file_info(info, ent20, LAI_SOURCE, 'M', 'lchgt', LAI_YEAR, 'ent17', '1.1', &
    varsuffix='_checksum')
#endif
call chunker%nc_create1(io_lchgt_checksum, &
    weighting(chunker%wta1,1d0,0d0), &
    info%dir, info%leaf, info)


! Quit if we had any problems opening files
call chunker%nc_check('B04_veg_height')
#ifdef JUST_DEPENDENCIES
stop 0
#endif

! --------------------------------- main loop
! Use these loop bounds for testing...
! it chooses a land area in Asia

#ifdef ENTGVSD_DEBUG
do jchunk = dbj0,dbj1
do ichunk = dbi0,dbi1
#else
do jchunk = 1,chunker%nchunk(2)
do ichunk = 1,chunker%nchunk(1)
#endif

    call chunker%move_to(ichunk,jchunk)

    do jc = 1,chunker%chunk_size(2)
    do ic = 1,chunker%chunk_size(1)

        ! Compute overall NetCDF index of current cell
        ii = (ichunk-1)*chunker%chunk_size(1)+(ic-1)+1
        jj = (jchunk-1)*chunker%chunk_size(2)+(jc-1)+1

        io_lchgt_checksum%buf(ic,jc) = 0
        do k = 1,NENT20
            if (k == CV_WATER) then
                OHEIGHT = 0d0
            else
                OHEIGHT = FillValue   ! Default if nothing in this PFT
                if (io_lc(k)%buf(ic,jc) > 0) then
                    ! Lookup what the height should be
                    SHEIGHT = max(io_sim%buf(ic,jc), 0.) ! filter out negative
                    OHEIGHT = SHEIGHT * heights_form(1,k) + heights_form(2,k)
                    io_lchgt_checksum%buf(ic,jc) = io_lchgt_checksum%buf(ic,jc) + &
                        io_lc(k)%buf(ic,jc) * OHEIGHT
                    ! TODO: Better way: inverse weighted average of
                    ! gridcell height, so tree heights are taller.  So
                    ! average gridcell height (averaging over non-zero
                    ! LC's) is same as the Simard height.
                end if
            end if

            io_out(k)%buf(ic,jc) = OHEIGHT
        end do    ! p

    end do    ! ic
    end do    ! jc
    
    call chunker%write_chunks

end do ! ichunk
end do ! jchunk

call chunker%close_chunks

      
#if (defined HGT_GEDI) || (defined HGT_POTAPOV)
end program gedi
#else
end program simard
#endif

